### ISSUE TITLE
can i at least host this on my own website/pc?

### ISSUE THREAD

**Issue by ftk789** [OpenPeepo/PointsTTS#4]
I want a free TTS brian points like this one, can i set it up? it doesn't work anymore bc of the new issue, so can i set it up locally?

**Comment by ThisIsIPat** [comment]
afaik, the new API made additional changes which i didnt look into much further.
To give you an idea where you could look yourself: https://textreader.pro/ supports TTS. Reverse engineering their approach probably will help you out.

Hosting this repo yourself doesn't change much, since it is a page that uses client-side requests in itself (Self-host still means client-side requests)
